AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Galashow API (Dev & Prod)

Parameters:
  StageNameParam:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Conditions:
  IsDev:  !Equals [ !Ref StageNameParam, dev ]
  IsProd: !Equals [ !Ref StageNameParam, prod ]

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:

  ### Dev API (only when StageNameParam=dev)
  DevApi:
    Condition: IsDev
    Type: AWS::Serverless::Api
    Properties:
      Name:      Galashow-dev
      StageName: dev
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  ### Prod API (only when StageNameParam=prod)
  ProdApi:
    Condition: IsProd
    Type: AWS::Serverless::Api
    Properties:
      Name:      Galashow-prod
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  DevBannerFunction:
    Condition: IsDev
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Banner/GalaShow.Banner.csproj
        Framework: net8.0
    Properties:
      FunctionName: DevBannerFunction
      CodeUri: src/GalaShow.Banner/
      Handler: GalaShow.Banner::GalaShow.Banner.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetBanners:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /banners
            Method: get
        UpdateBanner:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /banners/{bannerId}
            Method: put

  ProdBannerFunction:
    Condition: IsProd
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Banner/GalaShow.Banner.csproj
        Framework: net8.0
    Properties:
      FunctionName: ProdBannerFunction
      CodeUri: src/GalaShow.Banner/
      Handler: GalaShow.Banner::GalaShow.Banner.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetBanners:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /banners
            Method: get
        UpdateBanner:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /banners/{bannerId}
            Method: put

  DevTokenFunction:
    Condition: IsDev
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Token/GalaShow.Token.csproj
        Framework: net8.0
    Properties:
      FunctionName: DevTokenFunction
      CodeUri: src/GalaShow.Token/
      Handler: GalaShow.Token::GalaShow.Token.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /auth/login
            Method: post
        Refresh:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /auth/refresh
            Method: post
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /auth/logout
            Method: post
        Verify:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /auth/verify
            Method: get

  ProdTokenFunction:
    Condition: IsProd
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Token/GalaShow.Token.csproj
        Framework: net8.0
    Properties:
      FunctionName: ProdTokenFunction
      CodeUri: src/GalaShow.Token/
      Handler: GalaShow.Token::GalaShow.Token.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /auth/login
            Method: post
        Refresh:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /auth/refresh
            Method: post
        Logout:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /auth/logout
            Method: post
        Verify:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /auth/verify
            Method: get
            
            
  DevBackgroundFunction:
    Condition: IsDev
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.BackGround/GalaShow.BackGround.csproj
        Framework: net8.0
    Properties:
      FunctionName: DevBackgroundFunction
      CodeUri: src/GalaShow.BackGround/
      Handler: GalaShow.BackGround::GalaShow.BackGround.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetBackgroundVideos:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /background
            Method: get
        UpdateBackgroundVideo:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /background/{backId}
            Method: put
            
            
  ProdBackgroundFunction:
    Condition: IsProd
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.BackGround/GalaShow.BackGround.csproj
        Framework: net8.0
    Properties:
      FunctionName: ProdBackgroundFunction
      CodeUri: src/GalaShow.BackGround/
      Handler: GalaShow.BackGround::GalaShow.BackGround.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetBackgroundVideos:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /background
            Method: get
        UpdateBackgroundVideo:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /background/{backId}
            Method: put
  
  DevPolicyFunction:
    Condition: IsDev
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Policy/GalaShow.Policy.csproj
        Framework: net8.0
    Properties:
      FunctionName: DevPolicyFunction
      CodeUri: src/GalaShow.Policy/
      Handler: GalaShow.Policy::GalaShow.Policy.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetPolicy:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /policies
            Method: get
        UpdatePolicy:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /policies
            Method: put
            
  ProdPolicyFunction:
    Condition: IsProd
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Policy/GalaShow.Policy.csproj
        Framework: net8.0
    Properties:
      FunctionName: ProdPolicyFunction
      CodeUri: src/GalaShow.Policy/
      Handler: GalaShow.Policy::GalaShow.Policy.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetPolicy:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /policies
            Method: get
        UpdatePolicy:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /policies
            Method: put 

  DevSnsFunction:
    Condition: IsDev
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Sns/GalaShow.Sns.csproj
        Framework: net8.0
    Properties:
      FunctionName: DevSnsFunction
      CodeUri: src/GalaShow.Sns/
      Handler: GalaShow.Sns::GalaShow.Sns.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetPolicy:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /policies
            Method: get
        UpdatePolicy:
          Type: Api
          Properties:
            RestApiId: !Ref DevApi
            Path: /policies
            Method: put
  
  ProdSnsFunction:
    Condition: IsProd
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectFile: GalaShow.Sns/GalaShow.Sns.csproj
        Framework: net8.0
    Properties:
      FunctionName: ProdSnsFunction
      CodeUri: src/GalaShow.Sns/
      Handler: GalaShow.Sns::GalaShow.Sns.Function::FunctionHandler
      Runtime: dotnet8
      Policies:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      Events:
        GetPolicy:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /sns-links
            Method: get
        UpdatePolicy:
          Type: Api
          Properties:
            RestApiId: !Ref ProdApi
            Path: /sns-links
            Method: put
  
  ### Dev Custom Domain
  DevDomain:
    Condition: IsDev
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName:             api-dev.galashow.xyz
      RegionalCertificateArn: arn:aws:acm:ap-northeast-2:610495549763:certificate/2c301078-0b91-4d2b-b88c-6e1a643dab7c
      EndpointConfiguration:
        Types: [ REGIONAL ]

  ### Prod Custom Domain
  ProdDomain:
    Condition: IsProd
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName:             api.galashow.xyz
      RegionalCertificateArn: arn:aws:acm:ap-northeast-2:610495549763:certificate/2c301078-0b91-4d2b-b88c-6e1a643dab7c
      EndpointConfiguration:
        Types: [ REGIONAL ]

  ### Dev BasePathMapping
  DevBasePathMapping:
    Condition: IsDev
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: DevApidevStage
    Properties:
      DomainName: !Ref DevDomain
      RestApiId:  !Ref DevApi
      Stage:      dev
      BasePath:   ""

  ### Prod BasePathMapping
  ProdBasePathMapping:
    Condition: IsProd
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: ProdApiprodStage
    Properties:
      DomainName: !Ref ProdDomain
      RestApiId:  !Ref ProdApi
      Stage:      prod
      BasePath:   ""

  ### Dev DNS Record
  DevDNSRecord:
    Condition: IsDev
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z001166232XN5SLW00H6Z
      Name:         api-dev.galashow.xyz
      Type:         A
      AliasTarget:
        DNSName:      !GetAtt DevDomain.RegionalDomainName
        HostedZoneId: !GetAtt DevDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false

  ### Prod DNS Record
  ProdDNSRecord:
    Condition: IsProd
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z001166232XN5SLW00H6Z
      Name:         api.galashow.xyz
      Type:         A
      AliasTarget:
        DNSName:      !GetAtt ProdDomain.RegionalDomainName
        HostedZoneId: !GetAtt ProdDomain.RegionalHostedZoneId
        EvaluateTargetHealth: false
