  name: Deploy Galashow API
  
  on:
    workflow_dispatch:
      inputs:
        branch:
          description: "브랜치 선택"
          required: true
          default: "develop"
        stage:
          description: "Deploy Stage Select"
          required: true
          default: "dev"
          type: choice
          options:
            - dev
            - prod
  
  jobs:
    deploy:
      name: Deploy to ${{ inputs.stage }}
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout source code
          uses: actions/checkout@v4
          with:
            ref: ${{ inputs.branch }}
  
        - name: Set up .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '6.0'
  
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2
  
        - name: Install AWS SAM CLI
          uses: aws-actions/setup-sam@v2
  
        - name: SAM Build
          run: sam build
  
        - name: SAM Deploy
          run: |
            echo "Deploying to stage: ${{ inputs.stage }}"
            sam deploy --config-env ${{ inputs.stage }} --no-confirm-changeset --no-fail-on-empty-changeset
